//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDekerfsteve
{
    using System;
    using System.Collections.Generic;
    
    public partial class evenement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evenement()
        {
            this.inschrijvingen = new HashSet<inschrijving>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public string beschrijving { get; set; }
        public int locatie { get; set; }
        public System.DateTime datum { get; set; }
        public int Max_inschrijvingen { get; set; }
        public int Huidige_inschrijvingen { get; set; }
    
        public virtual Gemeente gemeente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inschrijving> inschrijvingen { get; set; }
    }
}
