//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDekerfsteve
{
    using System;
    using System.Collections.Generic;
    
    public partial class inschrijving
    {
        public int inschrijving_id { get; set; }
        public string persoon_id { get; set; }
        public int evenement_id { get; set; }
        public int aantal_personen { get; set; }
    
        public virtual evenement evenement { get; set; }
    }
}
